version: "3"

services:
  artifactory:
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-cpp-ce
    ports:
      - "9001:8081"
    volumes:
      - "artifactory:/var/opt/jfrog/artifactory"

  teamcity:
    container_name: teamcity
    image: jetbrains/teamcity-server
    ports:
      - "9002:8111"
    volumes:
      - "teamcity_data:/data/teamcity_server/datadir"
      - "teamcity_logs:/opt/teamcity/logs"

volumes:
  teamcity_data:
  teamcity_logs:
  artifactory: