version: "3"

services:
  artifactory:
    container_name: teste-ci-artifactory
    image: docker.bintray.io/jfrog/artifactory-oss
    ports:
      - "9001:8081"
    volumes:
      - "artifactory:/var/opt/jfrog/artifactory"

  teamcity:
    container_name: teste-ci-teamcity
    image: jetbrains/teamcity-server
    ports:
      - "9002:8111"
    volumes:
      - "teamcity-data:/data/teamcity_server/datadir"
      - "teamcity-logs:/opt/teamcity/logs"

  gitlab:
    container_name: teste-ci-gitlab
    image: gitlab/gitlab-ce
    ports:
      - "9003:80"
      - "9043:443"
      - "9022:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

volumes:
  teamcity-data:
  teamcity-logs:
  artifactory:
  gitlab-config:
  gitlab-logs:
  gitlab-data: