version: "3"

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss
    container_name: artifactory
    ports:
      - "9001:8081"
    volumes:
      - artifactory:/var/opt/jfrog/artifactory

  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    hostname: gitlab
    restart: always
    ports:
      - "9002:80"
      - "9042:443"
      - "9022:22"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    volumes:
      - gitlab-runner:/etc/gitlab-runner:Z
      - /var/run/docker.sock:/var/run/docker.sock

#  teamcity:
#    image: jetbrains/teamcity-server
#    container_name: teamcity
#    ports:
#      - "9003:8111"
#    volumes:
#      - "teamcity-data:/data/teamcity_server/datadir"
#      - "teamcity-logs:/opt/teamcity/logs"

#  maven:
#    container_name: maven
#    image: maven:3.3-jdk-8-alpine
#    volumes:
#      - ./ci-modulo-dependencia:/usr/src/build
#      - ./docker/settings.xml:/usr/share/maven/ref/settings.xml

volumes:
#  teamcity-data:
#  teamcity-logs:
  artifactory:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner: